name: 'Setup E2B Environment'
description: 'Sets up Python and E2B SDK for template operations'
runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install E2B SDK
      shell: bash
      run: pip install e2b